entero = 10
flotante = 3.14
cadena = "Hola, mundo"
verdadero = True
falso = False
lista = [1, 2, 3, 4, 5]
tupla = (1, "dos", True)
conjunto = {1, 2, 3, 4, 5}
diccionario = {"nombre": "Juan", "edad": 30}
